<<<<<<< HEAD
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./code:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_project
  php_project:
    build: .
    volumes:
      - ./code:/code
      - ./php/xdebug.conf:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_IDE_CONFIG: 'serverName=hdm'
=======
version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile  # Додаємо Dockerfile для PHP
    container_name: php
    volumes:
      - ./public:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini  # Шлях до xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    expose:
      - "9000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
>>>>>>> 476deed12a228f86b1338bc7b99e01f282395f27
