version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile  # Додаємо Dockerfile для PHP
    container_name: php
    volumes:
      - ./public:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini  # Шлях до xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    expose:
      - "9000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
